module.exports = [
	"Hope you're having an awesome day. Here's your dog of the day",
	"Hola, como estas? This lil fella wants to say hello",
	"Woof! ^_ ^",
	"Feeling down? Don't worry - we've got a dog for you",
	"Who's this guy? It's a dog!",
	"Knock knock. Who's there? Dog of the day, doofus!",
	"Cheer up, it's dog of the day.",
	"What day is it? Dog of the day!",
	"What has 4 legs and the joie de vivre of a mineral water advert? This guy!",
	"Don't have a dog day afternoon, have a dog of the day.",
	"Who says the internet is just for cats? It's dog of the day.",
	"Don't dither, dog of the day.",
	"Artistic, bankable, charming, dog of the day.",
	"It's dat DOD. (dog of the day)",
	"Keep your eyes on the price. Today's prize is a dog!",
	"New phone who dis? Dog!",
	"Dog CEO has business acumen to spare and a fleet of non-nonsense dogs that care.",
	"Your feed might be a torrent of promoted nonsense, but this dog is here to brighten it up for you",
	"Dog? Dog of the day!",
	"Dog CEO, giving dogging a new meaning since 2017 with 'Dog of the Day'",
	"Don't blog: Dog.",
	"It's not bog of the day, it's dog of the bay.",
	"What has a tail, 2 good eyes, 4 legs, and unending enthusiasm? This dog!",
	"All dogs are good dogs.",
	"There are no bad breeds only bad deeds. Dog of the day.",
	"Damn son, where'd you find this dog? Right here, doofus.",
	"Lessons one from the Dog CEO? Always start with a good dog.",
	"I like to start my day with a coffee, a scratch, and a look at the dog of the day. What's your morning routine, moguls?",
	"Dogs not mogs. Dog of the day.",
	"Dog CEO: taking you from boredom to the boardroom with dog of the day.",
	"You scratch my back and I'll scratch yours. RT todays dog of the day and Dog CEO will write you a good reference.",
	"Puppers? Doggos? Don't mess about, it's dog of the day.",
	"Busy day at the office? Take a paws for dog of the day"
]